### ISSUE TITLE
Styling the Graph

### ISSUE THREAD

**Issue by HamadAli248** [dunnock/react-sigma#102]
I'm trying to style the graph, I have fetched the data from the backend and passing it in but when I'm trying to style it to give nodes different colours and size it doesn't work, anyone has any ideas how I can customise the graph node colours and sizes for each node?
Here's the code I'm using to display the graph:

`{Object.keys(graphData).length > 0 && (`
`<Sigma`
`graph={cloneDeep(graphData)}`
`settings={{ drawEdges: true, clone: false }}`
 ` >`
 `<RelativeSize initialSize={15} />`
`<RandomizeNodePositions />`
`</Sigma>`
`)}` 

Thank You

**Comment by HamadAli248** [comment]
If anyone is looking to styling the graph without having to add the colours and sizes in the json, have a look at https://github.com/jacomyal/sigma.js/wiki/Settings

**Comment by dunnock** [comment]
Thank you
