### ISSUE TITLE
Get to the sigma instance

### ISSUE THREAD

**Issue by leofle** [dunnock/react-sigma#17]
I'm trying to get to the sigma instance to refresh the graph when i add a new Node.
how can i get to it?
i'm using also ForceAtlas2 how can i get to the API?

**Comment by dunnock** [comment]
Hi @leofle , you can implement your component and place it as child to Sigma, that component will receive sigma instance via props. You might want to check this reference as well: https://github.com/dunnock/react-sigma#extending-sigma-components
