### ISSUE TITLE
sigma.refresh() with a new graph hides the graph

### ISSUE THREAD

**Issue by RogerTangos** [dunnock/react-sigma#19]
When `Sigma` is passed a new `graph` prop and `sigma.refresh()` is called, the graph disappears.

// Instantiate Sigma with an existing graph
```
      <Sigma graph={this.props.graph} settings={{drawEdges:true}}>
         <RelativeSize initialSize={15}/>
         <RandomizeNodePositions/>
      </Sigma>
```

// update this.props.graph, which calls [`Sigma.componentDidUpdate()` and `Sigma.sigma.refresh()`](componentDidUpdate)

// The graph disappears from the screen, though the `Sigma.graph` object is updated

Maybe `Sigma.sigma` isn't able to handle other `Sigma.props` like `RelativeSize` or `RandomNodePosition`?

**Comment by dunnock** [comment]
Hi @RogerTangos, this is good spot and quite not trivial case to easily fix, Sigma.props.graph change at the moment does not restart subcomponents and I am not sure there is safe way to do that. I will put it as a improvement task for the future.

As possible solution you might create own Sigma sub component , which will get access to sigma instance via its props when places as child to Sigma, then you can place RelativeSize and RandomizeNodePositions under your component in JSX tree. You can trigger rendering RelativeSize and RandomizeNodePositions changing one of its props. Please note, you need to pass sigma instance further as props of children, [you can see how it is done in LoadJSON](https://github.com/dunnock/react-sigma/blob/master/src/LoadJSON.js#L61). Your final JSX will looks something like below.

```
<Sigma graph={this.props.graph} settings={{drawEdges:true}}>
    <YourGraphInitializerComponent>
         <RelativeSize initialSize={15}/>
         <RandomizeNodePositions/>
    </YourGraphInitializerComponent>
</Sigma>

```
[See example of your own sigma component]( https://github.com/dunnock/react-sigma#extending-sigma-components)

**Comment by RogerTangos** [comment]
Thanks, @dunnock - that was what I was looking for :)

**Comment by alx** [comment]
Hi @dunnock ,

I have the same issue with `sigma.refresh()`, and having an hard time finding what I've done wrong during the implementation of your solution, could you have a quick look and tell me what I'm doing wrong ?

Here is my component with a SigmaLoader PureComponent, its graph props is updated from a mobx observable :

```
<Sigma
          renderer={ appState.ui.renderer }
          onClickNode={ this.displayInfoBox }
          onClickStage={ this.hideInfoBox }
          style={styles.sigma}
        >
          <SigmaLoader graph={mobx.toJS(appState.selectedNetwork.graph)}>
            <RandomizeNodePositions>
              <Filter neighborsOf={ appState.graph.isFiltered ? appState.graph.selectedNode : null } />
              <ForceAtlas2 barnesHutOptimize barnesHutTheta={0.8} iterationsPerRender={2}/>
              <RelativeSize initialSize={15}/>
            </RandomizeNodePositions>
          </SigmaLoader>
</Sigma>
```
https://github.com/alx/parasol/blob/master/src/SigmaComponent.jsx#L42

Here is the SigmaLoader PureComponent, it's base on your LoadJSON one, but without calling and external sigma library:

https://github.com/alx/parasol/blob/master/src/SigmaLoader.jsx

Thanks and have a nice day,

Alex

**Comment by dunnock** [comment]
hi @alx, sorry for delay with answer..

I think this happens due to SigmaJSON unmounts all child components while loading graph, then when it mounts them back when graph is already loaded it forces components to go through reinitialization cycle (componentDidMount). Same can be achieved if you would change key for child components, e.g.

```
<RandomizeNodePositions key={graph.update_timestamp}>
```
I suggest to use graph update timestamp, you can use any other key, just don't change it if graph is the same, otherwise it will trigger false reinitialization.

Please let me know if that helped. 

Cheers, Maxim

**Comment by alx** [comment]
Hi @dunnock ,

Thanks for your answer, it's working great now when using `<RandomizeNodePositions/>` child component.

Would you know how to have the same result when `<RandomizeNodePositions/>` is not present as a child component ?

Have a nice day,

Alex

**Comment by dunnock** [comment]
@alx interesting, will look this weekend, perhaps some react-state issue

**Comment by alx** [comment]
Not sure if it's the nicest solution, but I've created a `<SigmaPluginsContainer/>` component that's basically the same component as `<RandomizeNodePositions/>` but without the randomized positions.

```
    if(network.options.randomizeNodePosition) {
      sigmaPlugins = <RandomizeNodePositions key={moment(network.timestamp).valueOf()}>{sigmaPlugins}</RandomizeNodePositions>
    } else {
      sigmaPlugins = <SigmaPluginsContainer key={moment(network.timestamp).valueOf()}>{sigmaPlugins}</SigmaPluginsContainer>
    }
```

https://github.com/alx/parasol/blob/dev/src/SigmaComponent.jsx#L68

**Comment by dunnock** [comment]
@alx probably that was also related to the graph nodes positions being reset.. If you update the graph with just node ids, all nodes positions get reset. Do you control nodes positions in your graph object? There is an option which can help you here, if you set <Sigma settings{{clone: false}} it should modify your supplied graph nodes (including setting positions) instead of cloning graph nodes, see https://github.com/jacomyal/sigma.js/wiki/Settings#graph-settings .. I did not try it this way, but might be good solution in your case!

**Comment by alx** [comment]
Thanks @dunnock , it's working great with this option.

**Comment by dunnock** [comment]
Perfect, thanks for confirming, will add this case to the doc!

**Comment by dunnock** [comment]
Updated doc
