### ISSUE TITLE
use with svg renderer?

### ISSUE THREAD

**Issue by Sigfried** [dunnock/react-sigma#20]
I'm trying to make a sigma.js graph with complex (and nested) react components as nodes. I think the only way to make this work is with something like the sigma.js svg renderer. When I came across this library, I hoped it might help, but maybe not...

There's a lot of great stuff here for integrating sigma into a react app, but I'm not sure how to accomplish my use case. Any suggestions?

**Comment by dunnock** [comment]
hi @Sigfried , do you mean you want to use declarative approach to define graph nodes right in JSX? The approach taken by this integration is a bit different, e.g. <Sigma> children supposed to be able to work with sigma directly, so they get passed sigma instance via props.

Potentially you can create React Component which given sigma instance would iterate react children elements tree using React.Children helpers and setup relevant graph in sigma instance via [sigma graph API](https://github.com/jacomyal/sigma.js/wiki/Graph-API).

For reference on how to implement such component you can check [LoadJSON.js](https://github.com/dunnock/react-sigma/blob/master/src/LoadJSON.js). After implementing such kind of a graph you should be able to apply other effects, like force atlas 2.

**Comment by dunnock** [comment]
No answer here, suppose issue is sorted?
