### ISSUE TITLE
Dependencies have several issues - missing dependencies, conflicting dependencies, out of date dependencies

### ISSUE THREAD

**Issue by jstafford** [dunnock/react-sigma#21]
I wanted to take a look at this package, so I cloned it. Unfortunately I missed the line in the Contributing readme about setting up for canvas (that might need to be highlighted a little more), so when I did "yarn install" I got the errors below. Since there were so many, I just started at the top.

- webpack dependency conflicting with webpack devDependency looks like the case of someone using an old version of yarn and doing a yarn add without the -D flag. Easy enough to update the devDependency to the newer version and remove webpack from the dependency list. 
- Same issue for whatwg-fetch.  
- While I was there I noticed that react and react-dom were both listed as dependencies and peerDependencies, when clearly they should have been devDependencies and peerDependencies. -- The unmet dependency of @kadira/storybook-addons was easy to fix. 
- react-dev-utils 0.3.0 depending on webpack 1 was easy to fix by going up to 0.5.2.
- ajv-keywords having the wrong peer dependency on ajv had me stumped for a while, but it was a problem with the versions in the yarn.lock file that was fixed with a "yarn upgrade"

Finally I got to the real failure and it still wasn't fixed. I decided to go ahead and upgrade everything else, thinking that would surely fix the problem. Of course it didn't. Eventually I took a more careful look at the error message, and realized that all I needed to do was a "brew install pkg-config"

Long story short, I have a pull request to go along with this issue if you are interested in taking all or part of it.

`yarn install v0.21.3
warning react-sigma@1.2.17: "dependencies" has dependency "webpack" with range "^2.2.1" that collides with a dependency in "devDependencies" of the same name with version "2.2.0-rc.3"
warning react-sigma@1.2.17: "dependencies" has dependency "whatwg-fetch" with range "^2.0.1" that collides with a dependency in "devDependencies" of the same name with version "1.0.0"
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@kadira/storybook-addon-knobs@1.7.1" has unmet peer dependency "@kadira/storybook-addons@^1.3.0".
warning "@kadira/storybook-addon-options@1.0.1" has unmet peer dependency "@kadira/storybook-addons@^1.5.0".
warning "react-dev-utils@0.3.0" has incorrect peer dependency "webpack@^1.13.2".
warning "ajv-keywords@1.4.1" has incorrect peer dependency "ajv@>=4.10.0".
[4/4] 📃  Building fresh packages...
[1/2] ⠄ fsevents: info ok
[2/2] ⠄ canvas: spawn args   '-Goutput_dir=.' ]
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error /Users/jason/code/react-sigma/node_modules/canvas: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/jason/code/react-sigma/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@7.6.0 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jason/code/react-sigma/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jason/.node-gyp/7.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jason/.node-gyp/7.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jason/code/react-sigma/node_modules/canvas',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jason/code/react-sigma/node_modules/canvas
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by dunnock** [comment]
Awesome! Thank you @jstafford , that's kind of review that this project needed, merged in, will update the doc!

**Comment by jstafford** [comment]
Glad to help
