### ISSUE TITLE
Are edge arrows working? 

### ISSUE THREAD

**Issue by sebastialonso** [dunnock/react-sigma#23]
Adding `defaultEdgeArrow={'both'}` to the Sigma component does nothing. Is the sigma version included in the React component already compatible with the edge's arrow funcionality?

**Comment by dunnock** [comment]
Hi @sebastialonso , there is no such prop defaultEdgeArrow in the Sigma component. Please see [reference](https://github.com/dunnock/react-sigma/blob/master/DOCS.md#sigma) for the list of supported props. To configure default edges type you can add `<EdgeShapes>` subcomponent, please see [reference](https://github.com/dunnock/react-sigma/blob/master/DOCS.md#edgeshapes) for supported edge types. Pls let me know if that helps.

**Comment by sebastialonso** [comment]
Sorry, my mistake. Thanks for your response!
