### ISSUE TITLE
Plugin - dragNodes

### ISSUE THREAD

**Issue by Baransu** [dunnock/react-sigma#28]
I'm trying to add `dragNodes` plugin. But have error with internal `instanceof` check in dragNodes plugin. It's trying to check is renderer is svg renderer but `sigma.renderer` does not have svg property. Am I missing something? 
```js
// @flow

import React from 'react';
import '../sigma/plugins.dragNodes';

type Props = {
  sigma?: sigma
  // TODO: Add listeners
};

/**
  TODO: Add plugin description
**/

class DragNodes extends React.Component {
  props: Props;

  componentDidMount() {
    const s = this.props.sigma;
    if (s) {
      console.log(s, s.renderers, sigma.renderers);
      const dragListener = new sigma.plugins.dragNodes(s, s.renderers[0]);
      // TODO: Add listeners
    }
  }

  componentWillUnmount() {
    if (this.props.sigma) {
      sigma.plugins.killDragNodes(this.props.sigma);
    }
  }

  render = () => null;
}

export default DragNodes;
```

**Comment by yaderick** [comment]
the same error

**Comment by dunnock** [comment]
Hi, svg rendered was not included into the package to minimize size. I've added it as standalone component now, see https://github.com/dunnock/react-sigma#sigmaenablesvg, make sure to explicitly specify and import it.

Also added webpack export for sigma.plugins.dragNodes, after `yarn build` it will be under sigma/sigma.plugins.dragNodes.js so you can import it:

```
import '../sigma/sigma.plugins.dragNodes';
```

Did not test SVG renderer, please let me know if there are still issues.

**Comment by daphil19** [comment]
I am running into the following when trying to render when using SVG:
```
Failed prop type: Invalid prop `renderer` of value `svg` supplied to `Sigma`, expected one of ["webgl","canvas"].
```
As a result my Sigma instance doesn't add an SVG renderer, resulting in the issues described above.

FWIW, I'm also using a custom loader component as described in #19, though I don't think that should have any impact.

Any thoughts?

**Comment by dunnock** [comment]
Good spot! Should be fixed with react-sigma@1.2.20

**Comment by daphil19** [comment]
@dunnock I still seem to be having issues with trying to load with SVG. The warning is now gone (yay!) But it seems like Sigma is still deciding to use the default renderer instead.

Here's roughly what I'm doing:
```javascript

import { Sigma, SigmaEnableSVG } from "react-sigma";
import SigmaLoader from "./SigmaLoader";

...

//in render:
<Sigma renderer="svg">
  <SigmaLoader graph={this.props.data}>
    {other composed components}
  </SigmaLoader>
</Sigma>
```
Am I missing something here? I appreciate your help!!

**Comment by dunnock** [comment]
@daphil19 very good spot again! it was missing from index exports, so required explicit import by module path. Should work in your example with 1.2.21, just published.

<img width="558" alt="screen shot 2017-07-29 at 01 05 17" src="https://user-images.githubusercontent.com/1453344/28738092-379976de-73fa-11e7-8f70-28121916e891.png">
