### ISSUE TITLE
Graph container doesn't use whole width

### ISSUE THREAD

**Issue by prttstft** [dunnock/react-sigma#3]
Hi,

somehow the graph always moves 50% to the right. Whether the container spans the entire width or only 100px. You can see that if you add a red background as an inline-style to the <Sigma> component.

Screenshots: 
http://i.imgur.com/ojzFxwn.png
http://i.imgur.com/ttMmHsM.png

**Comment by dunnock** [comment]
Hi @prttstft, that's weird, never spot anything like this. Can you provide your sample please? Also what's your browser? Few ideas to debug below:

You might try to render it on canvas or webgl explicitly:
`<Sigma renderer="canvas"> ...`
and webgl
`<SigmaEnableWebGL/>
<Sigma renderer="webgl"> ...`

If you open sigmajs website, does it render their sample graphs correctly? http://sigmajs.org/

Also try the storybook I've just built, it uses same react-sigma component:
https://dunnock.github.io/react-sigma/

**Comment by prttstft** [comment]
Hi, thanks.

I found the problem, the parent component had `style={{ textAlign: 'center' }}` and this lead to the problem.

Thanks!

**Comment by dunnock** [comment]
Perfect, thanks
