### ISSUE TITLE
React 15.5.0 deprecation warnings

### ISSUE THREAD

**Issue by osela** [dunnock/react-sigma#32]
Using this library in my project, I get the following warning on my console: "Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.".

The problem is that the version of babel-plugin-flow-react-proptypes you use is quite old, and still uses React.PropTypes when generating propTypes, instead of using the new separate prop-types package.

This could be easily fixed by upgrading to a newer version of the plugin and publishing a new version to npm.

**Comment by dunnock** [comment]
This was upgraded BTW, just forgot to close this issue.
