### ISSUE TITLE
sigma.plugins.dragNodes.js Question

### ISSUE THREAD

**Issue by bt2414** [dunnock/react-sigma#38]
I am wondering if you can provide some examples for how to use this plugin?

For example:

            <Sigma graph={graph} settings={{drawEdges: true, clone: false, animationsTime: 3000}} style={{width:"100%", height:"500px"}}>
              <ForceLink
                randomize="locally"
                barnesHutOptimize={false}
                barnesHutTheta={0.5}
                background
                easing="cubicInOut"
                gravity={1}
                edgeWeightInfluence={0}
                alignNodeSiblings={false}
                timeout={2000}
                outboundAttractionDistribution={false}
              />
              <RelativeSize initialSize={15}/>
              <RandomizeNodePositions/>
            </Sigma>

This is an example you provided in the website. How can I add the plugin into this Sigma element?

I know the interface should be: 

var dragNodesListener = sigma.plugins.dragNodes(s, s.renderers[0]);

But where to define the renderers?

I am sorry I am new to react-sigma. If you can provide a simple example for how to do dragnode, I will appreciate it.

Thank you so much.

**Comment by dunnock** [comment]
hi @bt2414, this plugin is not implemented as a component, so you will need to add yours like this one https://github.com/dunnock/react-sigma/blob/master/src/RelativeSize.js.

Also on top you will need to import dragNodes from sigma, replace relativeSize import with:
import 'sigma/sigma.plugins.dragNodes.js'

**Comment by bt2414** [comment]
Hi, @dunnock. Thanks so much and I make it work.
Also, I think there could be some more plugins right now we haven't been implemented, can I do it in the same way as the dragNodes plugin?

**Comment by dunnock** [comment]
Great, PR would be welcome! 

You can add easily plugins converted to CommonJS format by webpack: https://github.com/dunnock/react-sigma/blob/master/sigma-src/webpack.config.sigma.js

Also if it is not in the webpack configuration needs to be added there first. FYI it takes plugins source from sigma fork: https://github.com/dunnock/sigma.js/tree/master/plugins.

Closing this issue since it worked for you.
