### ISSUE TITLE
Using node properties as node position

### ISSUE THREAD

**Issue by alishir** [dunnock/react-sigma#39]
Is it possible to use node properties for example `x,y` properties, to fix node position in drawing?
I wanna use node properties as position instead of using drawing layouts,`FA, FA2, Randomized`.

**Comment by dunnock** [comment]
Yeah, absolutely, when you pass `<Sigma graph={obj}/>` in the obj.nodes you can define those properties:
```
let obj = {nodes:[{id:"n1", label:"Alice","x":255,"y":1737,"color":"rgb(0,204,204)","size":6}, {id:"n2", label:"Rabbit","x":155,"y":1000,"color":"rgb(0,204,204)","size":2}], edges:[{id:"e1",source:"n1",target:"n2",label:"SEES", "color":"rgb(204,0,0)"}]}
```

**Comment by alishir** [comment]
Thanks a lot @dunnock .
