### ISSUE TITLE
Cant npm install / npm build in local development

### ISSUE THREAD

**Issue by michaelghinrichs** [dunnock/react-sigma#46]
When trying to build the code, I am getting a webpack failure at the `npm install` step.

Here is the error:

```
> react-sigma@1.2.26 prepublish /Users/georgemichael/Code/react-sigma
> npm run build


> react-sigma@1.2.26 build /Users/georgemichael/Code/react-sigma
> babel-node scripts/build-cli.js

Error: Command failed: webpack --bail --config /Users/georgemichael/Code/react-sigma/sigma-src/webpack.config.sigma.js
(node:83839) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/is
sues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
ModuleNotFoundError: Module not found: Error: Can't resolve '/Users/georgemichael/Code/react-sigma/node_modules/sigma-react/plugins/sigma.layouts.forceLink/wo
rker.js' in '/Users/georgemichael/Code/react-sigma'
...
... bunch of stuff about Field `browser` doesn't contain a valid alias configuration
...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-sigma@1.2.26 build: `babel-node scripts/build-cli.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-sigma@1.2.26 build script.
```

**Comment by michaelghinrichs** [comment]
Update ->

npm run build:sigma _specifically_ is causing this issue.

It could be related to the fact that I am `npm link`ing things to work on this locally.

Do you have any advice on how to develop a change across both `sigma-react` and `react-sigma`? Having difficulties getting my code to compile...

**Comment by dunnock** [comment]
Did you mean you link other way around? `sigma-react` should be npm linked into `react-sigma`.

From the error it does not seems it was properly linked: `Can't resolve '/Users/georgemichael/Code/react-sigma/node_modules/sigma-react/plugins/sigma.layouts.forceLink/wo
rker.js'`

I have just git cloned both repos, run `npm link` from `sigma-react`, then `npm link sigma-react` from `react-sigma`, run `yarn`. All tests passed successfully. Can you please retry in a clean setup?

Anyways, Ive applied your change to `sigma-react@1.2.8`, perhaps you can sync version from npm.

**Comment by dunnock** [comment]
hi @michaelghinrichs , you were right, it seems module was already linked on my desktop and someplugins were not committed. fixed, please confirm

**Comment by dunnock** [comment]
hi @michaelghinrichs, please confirm if the issue resolved so I can close this

**Comment by dunnock** [comment]
I have retested this and it works
