### ISSUE TITLE
Slow <ForceLink> and <ForceAtlas2> on production build

### ISSUE THREAD

**Issue by andrius-kulbis** [dunnock/react-sigma#47]
I'm using standart webpack + react + babel + ES6 setup for my project. The following setup works well while running webpack-dev-server, the <ForceLink> transitions are smooth (nice UX), but the <ForceLink> gets slow, nodes hops from one position to another, it looks terrible while running production build of code. What may cause this kind of behaviour?

     const settings = {
         defaultNodeColor: "#3388AA",
         defaultEdgeColor: "#e9eef1",
         defaultLabelColor: "#777",
         labelThreshold: 7,
         hoverFontStyle: "text-size: 14",
         minNodeSize: 1,
         maxNodeSize: 10,
         zoomingRation: 10,
         maxRatio: 20,
         minRatio: 0.75,
    };

    <Sigma
        renderer="canvas"
        graph={graph}
        style={{width: '100%', height: "800px"}}
        settings={settings}
         onClickNode={e => this.setState({ selectedNode: e.data.node.id})}
         onClickStage={e => this.setState({selectedNode: null})}>
         <Filter
             neighborsOf={this.state.selectedNode}
             nodesBy={this.handleSearch.bind(this)}/>
          <ForceLink
              strongGravityMode={true}
              alignNodeSiblings={true}
              slowDown={10}
              iterationsPerRender={2}
              easing="cubicInOut"/>
       </Sigma>

**Comment by dunnock** [comment]
Can you check in the Inspector what actually rendered, is it Canvas or probably SVG. Maybe production build is running some dead code elimination, removing Canvas renderer? Issue is definitely with the webpack project setup, most likely with one of plugins. To find which webpack plugin causes the issue, try to turn them off one by one.

**Comment by andrius-kulbis** [comment]
Well the problem is caused by webpack  `UglifyJsPlugin`.

**Comment by dunnock** [comment]
@andrius-kulbis in such case you can pass option to UglifyJsPlugin to exclude sigma from optimization, something like:
```
new UglifyJsPlugin({
   exclude: [/.*node_modules.*sigma.*/],
   ... other options ...
})
```

**Comment by andrius-kulbis** [comment]
I managed to fix my problem by extracting `react-sigma` to separate chunk file, and excluding it from running through UglifyJsPlugin. Any idea why `react-sigma` breaks after uglify?

**Comment by dunnock** [comment]
Because it is built on top of Sigma.JS, which is using global variables a
lot. For instance, renderers are stored in global var and if no renderer it
falls back to default. Suppose Uglify might be marking such pieces as dead
code..

11 окт. 2017 г. 16:18 пользователь "Andrius Kulbis" <
notifications@github.com> написал:
