### ISSUE TITLE
Problem embedding Noverlap into Atlas2

### ISSUE THREAD

**Issue by JYCasalis** [dunnock/react-sigma#52]
Hi Maxim,

Not sure if I'm doing anything wrong as React is quite new to me but I'm facing an issue when trying to use Noverlap after ForceAtlas2.

Here's what I did:
```
<LoadJSON path="/data/pairsGraph_Group4.json">
    <RelativeSize initialSize={20}/>
    <RandomizeNodePositions/>
    <ForceAtlas2 scalingRatio={5}>
            <NOverlap/>
    </ForceAtlas2>  
</LoadJSON>
```

And here's what I get when executing my App:
![image](https://user-images.githubusercontent.com/9211839/33656830-9d8bbfe0-da77-11e7-9156-5667ccb3d93b.png)

Did I miss anything?

Thanks!

**Comment by dunnock** [comment]
Good spot! Fixed in react-sigma@1.2.30
