### ISSUE TITLE
Use react Context API to access the Sigma object

### ISSUE THREAD

**Issue by np** [dunnock/react-sigma#68]
Currently the sigma object is passed down as follows:
 
```
embedProps(this.props.children, {sigma: this.props.sigma})
```

This seems to me to be a perfect fit for the Context API https://reactjs.org/docs/context.html

**Comment by dunnock** [comment]
It's good idea, but not back compatible, it will break those who extended with own components as in the following example: https://github.com/dunnock/react-sigma#extending-sigma-components

Closing this as not likely will implement.
