### ISSUE TITLE
Example with Plugin sigma.neo4j.cypher

### ISSUE THREAD

**Issue by liobouchan** [dunnock/react-sigma#72]
Hello, dunnock! and friends, i used to use the Plugin on SigmaJS library for Neo4j named sigma.neo4j,cypher.js, but i dont understand how to use the component NeoCypher, i cant see the nodes of my query, but have no names and no edges of the graph, do you have an example of how to use it with a query like 'MATCH (n) RETURN n'

**Comment by dunnock** [comment]
Not sure what is the exact issue without looking at source code. But you might explore `NeoItemProducers` which called for every new node and edge.
