### ISSUE TITLE
Neo4Cypher example 

### ISSUE THREAD

**Issue by mafiqqq** [dunnock/react-sigma#78]
Hey everyone, I was having trouble to render Neo4Cypher to display my graph. From what i understood is that we need to declare the styles of each nodes and edges first at NeoGraphItemProducers? Then we need to call it using Neo4Cypher. (correct me if I'm wrong).

How do I write this code? Is there are any tutorial that I can follow?

Thank you in advance

**Comment by dunnock** [comment]
you could simply rely on default implementation of NeoGraphItemProducers:

```
  <Sigma renderer="canvas">
     <NeoCypher 
          url=".." 
          user=".." 
          password=".." 
          query=".." 
          onGraphLoaded={() => console.log("Graph loaded")} />
  </Sigma>
```

If you would want to overload default producers, just copy and change it to your needs keeping method signatures from here:
https://github.com/dunnock/react-sigma/blob/master/src/NeoGraphItemsProducers.js
Then pass instance of your implementation as `producers` property

**Comment by mafiqqq** [comment]
Thank you for your response...

![image](https://user-images.githubusercontent.com/32911977/69613802-26ffcf00-106d-11ea-8172-13c09fc0893d.png)

I've managed to call the nodes from Neo4j and display them. However, for the styling I need to adjust the property for EACH nodes available in my Neo4j database in NeoGraphItemProducers right?

Will it be like this for instance ...

node(node: Neo4jAccident) : SigmaAccident {
return {
                        id : node.id,
			label : node.properties.name,
			x : Math.random(),
			y : Math.random(),
			size : 1,
			color : this.colorsMap(node.labels[0]),
			neo4j_labels : node.labels,
			neo4j_data : node.properties
}
}

I'm still having trouble to get the information right from passing it from here then call it as producers in my NeoCypher. Would appreciate if you could help :) Thanks

**Comment by dunnock** [comment]
Correct, you can just copy and change class NeoGraphItemsProducers to your needs, e.g.

```
class MyNeoGraphItemsProducers {
	node(node: Neo4j$Node): Sigma$Node {
		return {
			id : node.id,
			label : node.properties.name,
			x : node.properties.x,
			y : node.properties.y,
			size : node.properties.size,
			color : node.properties.color,
			neo4j_labels : node.labels,
			neo4j_data : node.properties
		}
	}
	edge(edge: Neo4j$Edge): Sigma$Edge {
		return {
			id : edge.id,
			label : edge.type,
			source : edge.startNode,
			target : edge.endNode,
			color : "#333333", // or edge.properties.color or some function from edge.type
			neo4j_type : edge.type,
			neo4j_data : edge.properties
		}
	}
}
```

Then you could just pass instance to NeoCypher:

```
  <Sigma renderer="canvas">
     <NeoCypher 
          url=".." 
          user=".." 
          password=".." 
          query=".." 
          producers={new MyNeoGraphItemsProducers()}
          onGraphLoaded={() => console.log("Graph loaded")} />
  </Sigma>
```

**Comment by mafiqqq** [comment]
I tried to put it in NeoGraphItemsProducer but I'm having difficulties by getting such errors as "; expected" or " : expected"

Let say I have a node called Accident. 

node(Accident) : AccidentSigma {
   return {
                        id : Accident.accidentID,
			label : Accident.accidentDate		
                        x : Math.random(),
			y : Math.random(),
			size : 5,
			color : #5DA5DA,
			neo4j_labels : Accident.accidentDate,
			neo4j_data : Accident.accidentCity
   }
}

I'm having trouble understanding the code sample from the documentation. 
Where do I need to declare the class if I'm using React Component in my webapp?
The in-between process is the one that I'm stuck at. Will appreciate your help so much. Thank you in advance

**Comment by dunnock** [comment]
I will archive this in favour of https://github.com/dunnock/react-sigma/issues/81
