### ISSUE TITLE
edge arrow with svg renderer

### ISSUE THREAD

**Issue by siqixiong56** [dunnock/react-sigma#79]
Hi everyone,
Is there an example of how to use edges with arrowheads with svg renderer?
I was trying to add arrowheads to the lines but then the lines cannot move when dragging nodes and zooming in and out.

**Comment by dunnock** [comment]
@siqixiong56 [storybook has example with arrows,](https://dunnock.github.io/react-sigma/?knob-Outbound%20attraction%20distribution=false&knob-Barneshut%20theta=0.5&knob-Timeout=2000&knob-Easing%20after%20layout=cubicInOut&knob-Randomize%20node%20positions=locally&knob-Barneshut%20optimize=false&knob-Force%20layout%20in%20backround=true&knob-Gravity=1&knob-Edge%20weight%20influence=0&knob-Align%20node%20siblings=false&selectedKind=Plugins&selectedStory=Edge%20Labels&full=0&down=1&left=1&panelRight=1&downPanel=storybook%2Factions%2Factions-panel).

To force rerendering you may call sigma.refresh(), how do you drag nodes and/or zoom-in/out?

**Comment by siqixiong56** [comment]
But the example in the storybook is using canvas. The curvedArrow edge shape cannot be used with svg.
I used the drag nodes plugin.
