### ISSUE TITLE
Graph not rendering

### ISSUE THREAD

**Issue by Giulio64** [dunnock/react-sigma#89]
Hello, I'm trying to implement the library using React, here is a simple example inside a Crowd component:

```
import React, { Component } from "react";

    import {Sigma, RandomizeNodePositions, RelativeSize} from 'react-sigma';
    
    
    /**
     * Class to display to a user the dashboard of his/her museum
     * @author Giulio Serra
     */
    export default class Crowd extends Component {
        
        render(){
            let myGraph = {nodes:[{id:"n1", label:"Alice"}, {id:"n2", label:"Rabbit"}], edges:[{id:"e1",source:"n1",target:"n2",label:"SEES"}]};
            return <div><Sigma graph={myGraph} settings={{drawEdges: true, clone: false}}>
            <RelativeSize initialSize={15}/>
            <RandomizeNodePositions/>
          </Sigma></div>
        }
    }
```
Here is a picture:
![UqwrW](https://user-images.githubusercontent.com/32596004/85944117-cacb9900-b934-11ea-84c0-5b4c03da805e.jpg)

Am I missing something?Thanks

**Comment by jamjar919** [comment]
This component worked fine for me - I suspect you might not be rendering the graph in the right place in the rest of your app or something similar.

**Comment by Giulio64** [comment]
Relsoved the issue a while ago, you can close it.
