### ISSUE TITLE
Sigma wont Render graph after data passed from a fetch request response 

### ISSUE THREAD

**Issue by HamadAli248** [dunnock/react-sigma#98]
Hi,

I’m having issues with using sigma.js to display the graph, i have been able to fetch the results from the backend and it’s all correct as i logged to the console it’s printing out what i expect (json of node and edges) but won’t render the graph, to see if the results are correct I added the same results into a json file and tested it out from importing the file and that works. from debugging i couldn’t find anything wrong with the code as i’ve logged the result state  at each stage and it has the json object after the fetch request has been made also theres no errors in the console or anything, the only difference I could find is when rendering the file sigma added the following to the nodes

`cam0:size: 1.195503270717281`
`cam0:x: 151.2125270891966`
`cam0:y: 205.21931189133983`

but not for the fetch data as seen in the screenshots. Any ideas why this is being done for one but not the other? And how it can be fixed?

**Comment by dunnock** [comment]
Hi, how do you pass graph to the sigma? also if you can give example that would help

**Comment by HamadAli248** [comment]
Hi @dunnock so i used a fetch request to pull the data and using set state added it to a state var and added the state value in the sigma graph so e.g
`this.state = {`
 `   resultData: {},`
`  };`

then when i got the response i set the state value 
`this.setState({ resultData: response });`

finally when rendering i just called the state value and set to the graph 
`<Sigma graph={this.state.resultData} settings={{drawEdges: true, clone: false}}>`
 `  <RelativeSize initialSize={15}/>`
`  <RandomizeNodePositions/>`
` </Sigma>`

**Comment by dunnock** [comment]
Not sure what may be causing that, one idea is it might be due to the container size, e.g. div tag or where this sigma getting rendered. Did you check with browser tools that Sigma occupies proper area on a page?

**Comment by HamadAli248** [comment]
I have managed to fix it so the graph is rendering before the data is fetched so if anyone else has this issue you need to in the return div add a condition that the graph only renders when it has a value in the state and in the initial state the value should be set to null
